### ISSUE TITLE
checkOrderCallback does not work

### ISSUE THREAD

**Issue by ghost** [mariodian/geary#6]
The signatures never match. I guess the bug is somewhere in the code that calculates the signature before comparing it.

**Comment by mariodian** [comment]
Can you perhaps try it without this change? 35cb518

**Comment by rizhenkov** [comment]
Confirm. Does not work checking too. "Signature mismatch", but key/secret correct.

**Comment by nextgenthemes** [comment]
Same here, I get empty $order variable.

I also get `PHP Notice:  Undefined index: REDIRECT_URL` The function falls back to script name then I not really understand this. I would really appreciate a fix.

**Comment by nextgenthemes** [comment]
@mariodian I tried commenting out 35cb518 but it does not work.

I placed a 50$ bounty on this: https://www.bountysource.com/issues/49674995-checkordercallback-does-not-work

First time doing bountysource, I expected a bountysource bot to post this.

**Comment by pennycoders** [comment]
Hi @nextgenthemes, @mariodian ,

I have fixed this and created a pull request. I have tested it and everything and the signature checks out.

Please use the following code samples to test it out:

```php
<?php
error_reporting(E_ALL);
require_once('Geary.php');

$gateway_id = '{mycellium_gateway_id}';
$gateway_secret = '{mycellium_gateway_secret}';

$price = 1.00;

$ch = curl_init();

$geary = new Geary($gateway_id, $gateway_secret);

$keychain_id = 1;

if (empty($_GET)) {
  $order = $geary->create_order($price, $keychain_id,'foo');

  if ($order->payment_id) {
      die("<a href=\"https://gateway.gear.mycelium.com/pay/{$order->payment_id}\" target='_blank'>Pay</a> ");
}
} else {
  echo(json_encode($geary->check_order_callback()));
}

```

P.S: Use testnet coins for easier testing, and also, replace the {mycellium_gateway_id}
 and {mycellium_gateway_secret} placeholder with your own, after creating a Mycellium gear account that is testnet enabled;

Thanks,

Alex.

**Comment by nextgenthemes** [comment]
@pennycoders Awesome, thanks. It works! I not tested your example code but my implementation.

Just by looking at it `$ch = curl_init();` line seems to have purpose.

**Comment by pennycoders** [comment]
Hi @nextgenthemes,

The problem was within the Geary class (Please see my pull request), not the code which was using it. @mariodian, can you please accept my PR so we can close this issue ?

Also, if you need help testing it, maybe I can be of help.

Cheers!

**Comment by nextgenthemes** [comment]
@pennycoders Obviously I know that the problem was in the Geary class. I tested your PR in a WordPress plugin I am working on and it works (as I already said above)

@mariodian was very fast in pulling my last PRs. Its weekend, he will probably not take long to pull it. Enjoy your bounty.

**Comment by pennycoders** [comment]
Cool. Glad you got it sorted out! hehe.

**Comment by mariodian** [comment]
@nextgenthemes thanks for the fix. I tested it and it works. Merged.

The funny thing is my original code works on my local machine (I have the same PHP settings on my remote server and it works there too. 

Either way, your solution is cleaner.
